/** README ******************************************************************************************************************************************
 * This file is responsible for copying the task list generated by the current profile to the profile specific note for use when the panel or       *
 * plugin isnt available, such as on mobile devices.                                                                                                *
 ***************************************************************************************************************************************************/

/** Imports ****************************************************************************************************************************************/
import { getProfile } from "./database"
import { formats } from "./formats"
import { getNoteContent, setNoteContent } from "./joplin"
import { getCurrentProfileID } from "./settings"

/** Variable Declaration ***************************************************************************************************************************/
var baseMarkDown = `# <<PROFILE_NAME>>\n<<TODOS>>`

/** refreshNoteData *********************************************************************************************************************************
 * Saves the todo list as generated by the current profile to the profile specific note                                                             *
 ***************************************************************************************************************************************************/
export async function refreshNoteData(){
    var profileID = await getCurrentProfileID()
    var profile = await getProfile(profileID)
    if (profile.noteID) {
        var note = await getNoteContent(profile.noteID)
        if (note != undefined){
            var formatter = new formats[profile.displayFormat](profile, 'markdown')
            var todosMd = await formatter.getTodos()
            var markdownString = baseMarkDown.replace("<<PROFILE_NAME>>", profile.name)
            var markdownString = markdownString.replace("<<TODOS>>", todosMd)
            await setNoteContent(profile.noteID, markdownString)
        }    
    }
}
